### ISSUE TITLE
Arbitrary configuration loading

### ISSUE THREAD

**Issue by pduersteler** [Setono/deployer-cron#24]
Hi

Thanks for this deployer addon, really helpful!

I just set it up in a local project and wanted to put the jobs.yaml into the root directory instead of cluttering the project setup with an `etc/*` folder that wouldn't be used otherwise – most of the configs, like the deployer configuration files, are in the project root anyways.

I discovered that the deployment always failed because deployer-cron tried to load any file from the configured directory; .sql, .md, other .yml files, etc. I think it would be a better solution to either have a fixed filename or some sort of resolver for files that is restricting to certain file types. Loading SQL files wouldn't be a use case in the real world anyway.

**Comment by loevgaard** [comment]
Yeah, this is right. Would be better to make that configurable somehow. Can you come up with a PR? :)

**Comment by pduersteler** [comment]
I'll check if I find some time in between restructuring all the chaos projects I've been assigned to.. ^^

**Comment by loevgaard** [comment]
Perfect, thanks :)

**Comment by loevgaard** [comment]
I just released an alpha version that supports v7. This should also fix this issue
